import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import PageShell from '@/components/layout/PageShell';
import CTA from '@/components/sections/CTA';
import JsonLd from '@/components/seo/JsonLd';
import { caseStudies } from '@/content/work';
import { generateSEO } from '@/lib/seo';
import { siteConfig } from '@/content/site';
export function generateStaticParams(){ return caseStudies.map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> { const {slug}=await params; const project=caseStudies.find((item)=>item.slug===slug); return project ? generateSEO({title:`${project.title} Case Study`,description:project.summary,canonical:`/work/${project.slug}`}) : {}; }
export default async function WorkDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const project=caseStudies.find((item)=>item.slug===slug); if(!project) notFound(); const schema={'@context':'https://schema.org','@type':'CreativeWork',name:project.title,description:project.summary,url:`${siteConfig.url}/work/${project.slug}`,creator:{'@type':'Organization',name:siteConfig.name}}; return <PageShell><JsonLd data={schema}/><article className="pb-24 pt-36"><div className="container mx-auto max-w-4xl px-4"><p className="text-sm font-bold uppercase tracking-[0.18em] text-secondary">{project.label} · {project.status}</p><h1 className="mt-4 text-5xl font-bold tracking-tighter sm:text-7xl">{project.title}</h1><p className="mt-6 text-xl leading-8 text-muted-foreground">{project.summary}</p><div className="mt-14 space-y-10"><section><h2 className="text-3xl font-bold">Challenge</h2><p className="mt-4 leading-8 text-muted-foreground">{project.challenge}</p></section><section><h2 className="text-3xl font-bold">Solution</h2><p className="mt-4 leading-8 text-muted-foreground">{project.solution}</p></section><section><h2 className="text-3xl font-bold">Technology and capabilities</h2><div className="mt-5 flex flex-wrap gap-3">{project.stack.map((item)=><span key={item} className="rounded-full border border-white/10 px-4 py-2">{item}</span>)}</div></section><section><h2 className="text-3xl font-bold">Services used</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground">{project.services.map((item)=><li key={item}>{item}</li>)}</ul></section></div></div></article><CTA/></PageShell> }
